Support for Pumpkaboo/Gourgeist pokemon variants in pokemon json data
Jerakin/p5e-data-conversion pull request #1
Opened 2020-08-28 21:19 UTC by magroader

Focusing on these two because they are the only unsupported pokemon with permanent variants.

2020-08-29 21:50 UTC, Jerakin requested changes
Have a few comments, they are mainly naming/style convention stuff. But I would also like to see line 314 to 341 thrown into a function called some thing like `add_variant_info(poke_by_name)` which transforms the Pokemon previously setup, to keep `convert_pdata` as readable as possible.

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +        def_type_by_variant = {}
Would be nice to have the names a bit clearer.
`def` is a keyword in Python which makes the name confusing. A "Bulbasaur" isn't a type of a Pokemon it is a species.

```python
variant_by_species = {}
default_poke_by_species = {}
default_species_by_variant = {}
```

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +        for name,variants in util.VARIANT_DATA.items():
Missing space after comma

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +        for name,poke in poke_by_name.items():
Missing space after comma

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +            def_poke = poke_by_name[def_type_by_variant[def_poke_by_type[type_name]]]
As the comment about maybe `default_poke` would make it easier to read in the context of python

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +                        raise Exception("When searching for variants, could not find pokemon of type '" + d["name"] + "'")
Python have quite a few ways format strings, this is my favorite as I find it cleaner and easy to read `raise Exception(f"When searching for variants, could not find pokemon of type {data['name']}")`

2020-08-29 21:50 UTC, Jerakin commented on converters/pokemon.py
> +                for d in variants:
I want bananas with the "naming" comments so might as well make this into a `data` or something more descriptive.

2020-08-29 21:50 UTC, Jerakin commented on util/util.py
> +    for k,v in other.items():
Missing space after comma

2020-09-07 14:38 UTC, magroader commented
All comments addressed!

2020-09-07 21:51 UTC, magroader commented
I just noticed a major issue here - the evolve.json, filter_data.json, and index_order.json are set up incorrectly. I at first though this was just because I didn't download the other .csv files, but it turns out this all came from PDATA. This will need some work!

2020-09-14 21:07 UTC, Jerakin commented
lgtm

2020-09-14 21:07 UTC, Jerakin approved these changes

2020-09-15 21:41 UTC, merged